### ISSUE TITLE
データベースにデータを登録しよう

### ISSUE THREAD

**Issue by shiotomo** [git-Ktu/rails_sample#2]
###  内容

- データベースにORMを利用してPOSTされたデータを保存します。

### ルーティング

- blogs/index
- blogs/new
- blogs/create
- blogs/show

### 実装機能

- Blogテーブルにデータを保存してください
- テーブルの内容は以下のとおりです。

|名前|型|
|--|--|
|title|string|
|body|text|

**Comment by git-Ktu** [comment]
完成したがcommitのコメントで「#2」とつけていなかったためここに表示されていない。
git commit -m "blog/indexに登録したデータをすべて表示 #2"
上記のコマンドを実行したがブラウザで見た時変更されていなかった。
gitよくわからない。
https://rails-study.net/index-view/
ここをみてやった。

**Comment by shiotomo** [comment]
目標を達成できているのでissueをcloseします。
